"""empty message

Revision ID: 372052884d42
Revises: 62fff3b2500c
Create Date: 2023-11-02 01:50:18.051330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372052884d42'
down_revision = '62fff3b2500c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_constraint('venta_cliente_id_fkey', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('venta_cliente_id_fkey', 'cliente', ['cliente_id'], ['id'])

    # ### end Alembic commands ###
