"""empty message

Revision ID: 62fff3b2500c
Revises: 8c6c36eeb9d0
Create Date: 2023-11-02 01:41:30.479861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fff3b2500c'
down_revision = '8c6c36eeb9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedor_venta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor_venta',
    sa.Column('vendedor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('venta_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], name='vendedor_venta_vendedor_id_fkey'),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], name='vendedor_venta_venta_id_fkey')
    )
    # ### end Alembic commands ###
