"""empty message

Revision ID: 8c6c36eeb9d0
Revises: 9c247cd35070
Create Date: 2023-11-02 01:06:42.158041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6c36eeb9d0'
down_revision = '9c247cd35070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedor_venta',
    sa.Column('vendedor_id', sa.Integer(), nullable=True),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['vendedor.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedor_venta')
    # ### end Alembic commands ###
