# Generated by Django 4.2.6 on 2023-10-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendedor', '0001_initial'),
        ('Coche', '0002_alter_coche_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coche_vendido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coche.coche')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendedor.vendedor')),
            ],
        ),
    ]
