# Generated by Django 4.2.6 on 2023-10-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave_licencia', models.CharField(max_length=20)),
                ('edad', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
    ]
