# Generated by Django 4.2.6 on 2023-10-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Conductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('year_fabricacion', models.PositiveIntegerField()),
                ('numeroplaca', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conductor.conductor')),
            ],
        ),
    ]
