# Generated by Django 4.2.6 on 2023-10-28 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MarcaCoche', '0001_initial'),
        ('Coche', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarcaCoche.marcacoche'),
        ),
    ]
