# Generated by Django 4.2.6 on 2023-10-28 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coche', '0002_alter_coche_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('cambio_aceite', 'Cambio de Aceite'), ('revision_frenos', 'Revisión de Frenos'), ('otros', 'Otros')], max_length=50)),
                ('fecha_servicio', models.DateField()),
                ('costo_servicio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_servicio', models.TextField()),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coche.coche')),
            ],
        ),
    ]
