"""empty message

Revision ID: a55e5ed999bd
Revises: 
Create Date: 2023-11-06 11:18:35.779915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55e5ed999bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreciudad', sa.String(length=250), nullable=True),
    sa.Column('estadociudad', sa.String(length=250), nullable=True),
    sa.Column('paisciudad', sa.String(length=250), nullable=True),
    sa.Column('poblaciontotal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marcacoche', sa.String(length=250), nullable=True),
    sa.Column('modelocoche', sa.String(length=250), nullable=True),
    sa.Column('paisorigen', sa.String(length=250), nullable=True),
    sa.Column('color', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('juguete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombrejuguete', sa.String(length=250), nullable=True),
    sa.Column('nombreproveedor', sa.String(length=250), nullable=True),
    sa.Column('precioventa', sa.Integer(), nullable=True),
    sa.Column('cantprodvendidos', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mascota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombremascota', sa.String(length=250), nullable=True),
    sa.Column('razamascota', sa.String(length=250), nullable=True),
    sa.Column('colormascota', sa.String(length=250), nullable=True),
    sa.Column('edadmascota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreprofesor', sa.String(length=250), nullable=True),
    sa.Column('apellidosprofesor', sa.String(length=250), nullable=True),
    sa.Column('materiaprofesor', sa.String(length=250), nullable=True),
    sa.Column('correoprofesor', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profesor')
    op.drop_table('mascota')
    op.drop_table('juguete')
    op.drop_table('coche')
    op.drop_table('ciudad')
    # ### end Alembic commands ###
