"""empty message

Revision ID: ab2d800396c6
Revises: 1451917f1e2b
Create Date: 2023-11-29 20:32:14.892304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab2d800396c6'
down_revision = '1451917f1e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text1', sa.Text(), nullable=True),
    sa.Column('text2', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticia')
    # ### end Alembic commands ###
